# Generated by Django 3.0.4 on 2020-03-08 23:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Zsa-z\\s]*$', 'Only alphabets and spaces are allowed.')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Zsa-z\\s]*$', 'Only alphabets and spaces are allowed.')], verbose_name='last name'),
        ),
    ]
